name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run_unit_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
          - 18.x
        os:
          - linux-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
