name: Run tests

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - main

jobs:
  run_unit_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  publish_to_npm:
    runs-on: ubuntu-latest
    needs:
      - run_unit_test
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
